version: '3.9'


x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-06-13T22-53-53Z
  command: server --console-address ":9001" http://minio{1...2}/data{1...2}
  expose:
    - "9000"
    - "9001"
  deploy:
    resources:
      limits:
        cpus: '0.5'  
        memory: 512M 
    restart_policy:
      condition: on-failure
      max_attempts: 3
      delay: 10s
  networks:
    - minio-network

services:
  postgres:
    # container_name: auth-storage
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-storage
      PGDATA: /data/postgres
    restart: unless-stopped
    expose:
      - "5432"
    networks: 
      - auth-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - auth-network

  auth-migrate:
    image: migrate/migrate
    volumes:
      - ../auth/migrations:/migrations
    entrypoint: [
      "migrate", "-path", "/migrations", "-database",
      "postgres://postgres:postgres@postgres:5432/auth-storage?sslmode=disable", "up"
    ]
    restart: on-failure
    depends_on:
      - postgres
    networks: 
      - auth-network

  auth:
    container_name: auth-service
    image: auth
    build:
      context: ../auth
      dockerfile: dockerfile
    ports:
      - "50051:50051"
    restart: unless-stopped
    depends_on:
      - postgres
      - auth-migrate
    networks: 
      - gateway-network
      - auth-network
    volumes:
      - ../auth/config.yml:/app/config.yml

  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./html:/srv

    networks:
      - gateway-network

  files:
    image: fileshare/files:latest
    build:
      context: ../files
      dockerfile: dev.dockerfile
    depends_on:
      - minio1
      - minio2
    expose:
      - 50051
    # ports: 
      # - 50051:50051
    volumes:
      - ../files/config.yml:/root/config.yml
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        limits:
          cpus: '0.5'  
          memory: 512M
    networks:
      - minio-network
      - gateway-network

  gateway:
    image: fileshare/gateway:latest
    build:
      context: ../gateway
      dockerfile: dev.dockerfile
    depends_on:
      - files
    volumes:
      - ../gateway/config.yml:/root/config.yml
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        limits:
          cpus: '0.5'  
          memory: 512M
    networks:
      - gateway-network

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
    networks:
      - minio-network

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:

networks:
  auth-network:
    driver: bridge
  minio-network:
    driver: bridge
  gateway-network:
    driver: bridge
  

